name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend deps
        run: cd frontend && npm install

      - name: Install backend deps
        run: cd backend && pip install -r requirements.txt

      - name: Run tests
        run: echo "Aquí correrías jest/pytest"
